name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch full history to get commit logs

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install Dependencies
        run: |
          # Install Helm
          curl -fsSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          # Install git-chglog
          GIT_CHGLOG_VERSION=0.15.1  # Replace with the latest version
          curl -sSL https://github.com/git-chglog/git-chglog/releases/download/v${GIT_CHGLOG_VERSION}/git-chglog_${GIT_CHGLOG_VERSION}_linux_amd64.tar.gz | tar -xz -C /usr/local/bin git-chglog

      - name: Generate per-chart CHANGELOG.md files
        run: |
          for chart_dir in charts/*/; do
            chart=$(basename $chart_dir)
            echo "Processing chart: $chart"
            # Get the latest tag for this chart
            last_tag=$(git tag --list "${chart}-*" --sort=-v:refname | head -n 1)
            if [ -z "$last_tag" ]; then
              echo "No previous tag found for $chart. Generating changelog from beginning."
              range=""
            else
              echo "Found last tag for $chart: $last_tag"
              range="${last_tag}..HEAD"
            fi
            # Generate the changelog
            git-chglog --config .chglog/config.yml --output $chart_dir/CHANGELOG.md $range -- $chart_dir
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        with:
          charts_repo_url: https://itzg.github.io/minecraft-server-charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
